trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'src' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/BoE-$(Build.BuildId).love' 
- task: PublishPipelineArtifact@1
  inputs:
    path: '$(Build.ArtifactStagingDirectory)/BoE-$(Build.BuildId).love'
